export enum USER_ROLES {
  SUPER_ADMIN = 'SUPER_ADMIN',
  BROTHER = 'BROTHER',
  SISTER = 'SISTER',
}

export enum USER_STATUS {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  RESTRICTED = 'RESTRICTED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
  DELETED = 'DELETE',
}
